NEURON_ENERGY_LOSS_RATE_MUTATION_PROB = 1 / 10
NEURON_ENERGY_LOSS_SIGMA = 0.1

AXON_ENERGY_POTENTIAL_MUTATION_PROB = 1 / 10
AXON_ENERGY_POTENTIAL_SIGMA = 0.1

AXON_WEIGHT_MUTATION_PROB = 1 / 10
AXON_WEIGHT_SIGMA = 0.1

NEW_AXON_MUTATION_PROB = 1 / 20

historical_neuron_genes = []
historical_axon_genes = []
